### ISSUE TITLE
How you implement bcast?

### ISSUE THREAD

**Issue by chuqingG** [asonnino/hotstuff#66]
Hey, I just wonder whether you just done it by:
```Rust
// consensus/src/synchronizer.rs
let message =  NetMessage(Bytes::from(bytes), addresses);
network_channel.send(message).await;
```
If so, why a simple `send()` can achieve it, I found it in [doc](https://docs.rs/tokio/1.15.0/tokio/sync/mpsc/struct.Sender.html) that the  only parameter will just be handled as a message.
If not, then how can the protocol achieve it?

Looking forward to your kind reply 😃

**Comment by chuqingG** [comment]
Oh sorry I noticed that your repo is still being updated these days 😢 maybe I should turn to the latest one

**Comment by asonnino** [comment]
Hi, yes I try to update the repo regularly but I also try to keep the `main` branch stable. Although I just updated it recently to get a nice performance boost (and I believe the code is more readable now). The other branches are less stable, particularly the ones that mention they only supplement papers.

Here is how the synchronizer sends messages through the (new) network. There are 2 different *tokio tasks* (if this is confusing, just consider there are 2 threads):

1.  The synchronizer task holds a network struct called `network`: https://github.com/asonnino/hotstuff/blob/b5faa104f453c5cfffc0fd58441d0eb196c5659a/consensus/src/synchronizer.rs#L3 To send a message, this network struct passes a message to another tokio tasks that handle a network connection with a specific peer.
2. The second task checks if the TCP channel with the selected per is alive. If it is it sends the message, otherwise it tries to reconnect: https://github.com/asonnino/hotstuff/blob/b5faa104f453c5cfffc0fd58441d0eb196c5659a/network/src/simple_sender.rs#L61

**Comment by chuqingG** [comment]
> Hi, yes I try to update the repo regularly but I also try to keep the `main` branch stable. Although I just updated it recently to get a nice performance boost (and I believe the code is more readable now). The other branches are less stable, particularly the ones that mention they only supplement papers.
> 
> Here is how the synchronizer sends messages through the (new) network. There are 2 different _tokio tasks_ (if this is confusing, just consider there are 2 threads):
> 
> 1. The synchronizer task holds a network struct called `network`: https://github.com/asonnino/hotstuff/blob/b5faa104f453c5cfffc0fd58441d0eb196c5659a/consensus/src/synchronizer.rs#L3
>     To send a message, this network struct passes a message to another tokio tasks that handle a network connection with a specific peer.
> 2. The second task checks if the TCP channel with the selected per is alive. If it is it sends the message, otherwise it tries to reconnect: https://github.com/asonnino/hotstuff/blob/b5faa104f453c5cfffc0fd58441d0eb196c5659a/network/src/simple_sender.rs#L61

😄 looks good to me, thanks for your reply.
